name: yeat
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - black=22.10
    - fastp>=0.23
    - fastqc>=0.11
    - gzip>=1.7
    - mash>=2.3
    - megahit>=1.2
    - pandas>=1.4
    - pytest>=7.1
    - pytest-cov>=3.0
    - python=3.9
    - quast>=5.0
    - seqtk>=1.3
    - snakemake=7.32
    - pulp=2.7
    - spades>=3.15
    - unicycler>=0.4
    - versioneer>=0.21
    - canu>=2.2
    - flye>=2.9
    - nanofilt>=2.3
    - nanoplot>=1.20
    - hifiasm>=0.19
    - hifiasm_meta=hamtv0.2
    - gfatools>=0.5
    - plass>=4.687d7
    - samtools>=1.21
    - bowtie2>=2.5
    - pilon>=1.24
