name: yeat
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - black
    - fastp
    - fastqc
    - gzip
    - mash
    - pytest-cov
    - quast
    - seqtk
    - snakemake
    - spades
    - versioneer
